### ISSUE TITLE
Missing Documents folder in repo

### ISSUE THREAD

**Issue by th00masml** [nirbar1985/ai-travel-agent#4]
Hi there, in line85 of 1pp.py you added something like this

st.sidebar.image('/Users/Nir.Bar/Documents/demos/genai/langgraph/reflection-agent/images/ai-travel.png', caption='AI Travel Assistant')

What crashes app

MediaFileStorageError: Error opening '/Users/Nir.Bar/Documents/demos/genai/langgraph/reflection-agent/images/ai-travel.png'

![image](https://github.com/user-attachments/assets/16feb905-261c-4436-9704-bf5e5ccbb24b)

**Comment by nirbar1985** [comment]
Hi,
Fixed in version 0.1.1
Thanks!

**Comment by th00masml** [comment]
Np, keep doing good work
